### PR TITLE
Link the github repository in the note

### PR DESCRIPTION
**Pull request by OneShot-Niko**
Unless I'm doing this wrong (atleast as far as I read it the part I'm changing is HTML despite the file being .vue) this should be good to go

EDIT: Also as note I probably should've told you or asked first but i think it'd be best if you hyperlink the github repo on that note so issues don't have to only be told late if someone (somehow atleast) misses the repo

### CODE REVIEW

**Comment by mybearworld** [comment]
That's a good idea, thanks!
I'm using TailwindCSS though, which means that without further classes, that link will appear completely unstyled and just like the text around it. Could you add the classes `text-sky-400 underline` to the link, so it looks like all the other links on Roarer?

**Comment by OneShot-Niko** [comment]
> That's a good idea, thanks! I'm using TailwindCSS though, which means that without further classes, that link will appear completely unstyled and just like the text around it. Could you add the classes `text-sky-400 underline` to the link, so it looks like all the other links on Roarer?

Will do - That'd be <a href="URL HERE" class="text-sky-400 underline"> right?

**Comment by mybearworld** [comment]
Yep, thank you!

**Comment by OneShot-Niko** [comment]
> Yep, thank you!

Alrighty then!
No problem!!

**Pull request merged**
