### PR TITLE
[Groups] `Live chat` ---> `Livechat` (consistency)

### PR DESCRIPTION
**Pull request by OneShot-Niko**
consistency between meower-svelte and roarer on the name

this is definitely unneccasary so the branch name is sarcastic

### CODE REVIEW

**Comment by mybearworld** [comment]
Grammar-wise, "live chat" makes more sense though

**Comment by OneShot-Niko** [comment]
> Grammar-wise, "live chat" makes more sense though

It does, and this isn't really needed either - Just tomake sense between the two clients, though it's unnecassary.

**Comment by showierdata9978** [comment]
Livechat is the correct terminology

**Comment by mybearworld** [comment]
Alright then

**Pull request merged**
